apiVersion: apps/v1
kind: Deployment
metadata:
 name: api-deploy
 labels:
  type: api-backend
spec:
 template:
  metadata:
   name: api-app
   labels:
    type: api-backend
  spec:
   containers:
    - name: app-container
      image: sruthividya/node-task:1.0
      ports:
        - containerPort: 80
      env:
        - name: DB_HOST
          valueFrom:
           secretKeyRef:
             name: doc-secret
             key: DB_HOST
        - name: DB_USER
          valueFrom:
           secretKeyRef:
             name: doc-secret
             key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
           secretKeyRef:
             name: doc-secret
             key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
           secretKeyRef:
             name: doc-secret
             key: DB_DATABASE
        - name: DB_PORT
          valueFrom:
           secretKeyRef:
             name: doc-secret
             key: DB_PORT
        - name: PORT
          valueFrom:
           secretKeyRef:
             name: doc-secret
             key: PORT
 replicas: 1
 selector:
  matchLabels:
   type: api-backend

---

apiVersion: v1
kind: Service
metadata:
  name: api-backend
spec:
  selector:
    app: api-backend
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4001

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpuutilization
      target:
        type: Utilization
        averageUtilization: 40
 
